# Generated by Django 5.2.10 on 2026-01-23 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sleeper Express', max_length=100)),
                ('source', models.CharField(default='Ahmedabad', max_length=100)),
                ('destination', models.CharField(default='Mumbai', max_length=100)),
                ('departure_time', models.TimeField(default='22:00')),
                ('arrival_time', models.TimeField(default='06:00')),
                ('total_seats', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NONVEG', 'Non-Vegetarian'), ('SNACK', 'Snacks')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('seat_type', models.CharField(choices=[('LOWER', 'Lower Deck'), ('UPPER', 'Upper Deck')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=800.0, max_digits=6)),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('passenger_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('travel_date', models.DateField(default=django.utils.timezone.now)),
                ('pnr', models.CharField(editable=False, max_length=10, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('prediction_score', models.FloatField(blank=True, help_text='Booking confirmation probability', null=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.meal')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat')),
            ],
        ),
    ]
