# Generated by Django 5.2.10 on 2026-02-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('stop_number', models.IntegerField(help_text='Order of the stop')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.bus')),
            ],
            options={
                'ordering': ['stop_number'],
            },
        ),
    ]
