# Generated by Django 5.2.10 on 2026-02-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
    ]
