# Generated by Django 5.2.10 on 2026-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('SNACK', 'Snacks')], max_length=10),
        ),
    ]
