# Generated by Django 5.2.10 on 2026-03-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.busstop'),
        ),
    ]
