# Generated by Django 5.2.10 on 2026-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_dropoff_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ticket fare to this station (Overrides seat price if > 0)', max_digits=6),
        ),
    ]
